Made everything dark mode
kevinvgils/PatheAppP3 pull request #47
Opened 2022-04-05 18:26 UTC by UltimateThijs

Note to make future things dark mode: Use "@color/darkmode" to make it automatically switch between white and the dark mode color.

2022-04-05 18:38 UTC, kevinvgils requested changes
Goed begin alleen was dit niet helemaal de bedoeling er moet een switch komen waar als de gebruiker op drukt het darkmode moet worden in de app.

2022-04-05 18:52 UTC, goldo63 requested changes
In de homepagina heeft de filter switch een apparte achtergrond

2022-04-06 18:35 UTC, goldo63 approved these changes
I approve of this message

2022-04-06 18:36 UTC, kevinvgils approved these changes
lgtm!

2022-04-06 18:36 UTC, merged